name: PHPCS check

on: [push]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: YES
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs
      - name: Run phpcs
        run: phpcs --standard=PSR1,PSR12